nginx:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/issuer: letsencrypt-production
    hosts:
      - host: pbotapps-test.portland.gov
        paths:
          - path: /comms/public-involvement
    tls:
      - secretName: pbotapps-test-portland-gov-tls
        hosts:
          - pbotapps-test.portland.gov

files:
  storageClass: azurefile
  size: 8Gi
  accessModes:
    - ReadWriteMany

redis:
  persistence:
    enabled: true
    storageClass: managed-premium
    size: 8Gi
    accessModes:
      - ReadWriteOnce
