apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-fpm
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/name: "{{ include "chart.fullname" . }}-fpm"
type: Opaque
data:
  DATABASE_PASSWORD: {{ include "chart.databasePassword" . | b64enc | quote }}
