apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-redis
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/name: "{{ include "chart.fullname" . }}-redis"
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: "{{ include "chart.fullname" . }}-redis"
    app.kubernetes.io/component: redis
  ports:
    - name: {{ include "chart.fullname" . }}-redis
      protocol: TCP
      port: {{ .Values.redis.service.port }}
      targetPort: 6379
